spring:
  application:
    name: core

  profiles:
    group:
      api: api
      batch: batch
      admin: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/klaatus?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: klaatus
    password: 1234

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none                           # 스키마 자동 업데이트 update, create (운영 환경에서는 사용하지 말것)
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO                                   # 기본 로그 레벨
    org.springframework.web: DEBUG               # Spring Web 로그 레벨
    com.querydsl.sql: DEBUG

